import { useState, useRef, type DragEvent, type ChangeEvent } from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface MockFile {
  name: string;
  size: number;
  lastModified: string;
}

function formatBytes(bytes: number, decimals = 2) {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
}

function formatDate(dateString: string) {
  return new Intl.DateTimeFormat('en', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(dateString));
}

export function BusinessRecordImport() {
  const [file, setFile] = useState<MockFile | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDragOver = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  };

  const handleDragLeave = () => {
    setIsDragging(false);
  };

  const handleDrop = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);

    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      const droppedFile = e.dataTransfer.files[0];
      const extension = droppedFile.name.split('.').pop()?.toLowerCase();
      
      if (extension === 'md' || extension === 'markdown') {
        setFile({
          name: droppedFile.name,
          size: droppedFile.size,
          lastModified: new Date(droppedFile.lastModified).toISOString(),
        });
      } else {
        alert('Invalid file format. Please drop a .md or .markdown file.');
      }
    }
  };

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const selectedFile = e.target.files[0];
      setFile({
        name: selectedFile.name,
        size: selectedFile.size,
        lastModified: new Date(selectedFile.lastModified).toISOString(),
      });
    }
  };

  const handleBrowseClick = () => {
    fileInputRef.current?.click();
  };

  const handlePasteClick = () => {
    // Mock pasting markdown file
    setFile({
      name: 'pasted-business-record.md',
      size: 4620, // 4.5 KB
      lastModified: new Date().toISOString(),
    });
  };

  const handleReplaceFile = () => {
    setFile(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="mt-8 space-y-10">
      <AnimatePresence mode="wait">
        {!file ? (
          <motion.div
            key="dropzone"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            transition={{ duration: 0.2 }}
            className={`relative flex min-h-[22rem] flex-col items-center justify-center rounded-[var(--radius-xl)] border-2 border-dashed p-8 text-center transition-all ${
              isDragging
                ? 'border-action-primary bg-action-primary-subtle/30 shadow-[0_0_0_4px_var(--action-primary-subtle)]'
                : 'border-border-strong bg-surface-panel hover:border-action-primary/50'
            }`}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onDrop={handleDrop}
          >
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileChange}
              accept=".md,.markdown"
              className="sr-only"
              id="business-record-file-picker"
            />
            
            <div className="grid size-12 place-items-center rounded-[var(--radius-lg)] bg-action-primary-subtle font-display text-xl font-semibold text-action-primary">
              ↓
            </div>

            <h2 className="mt-5 font-display text-2xl font-semibold tracking-tight text-content-primary">
              Drop your Business Record here
            </h2>
            <p className="mt-2 max-w-sm text-sm leading-6 text-content-secondary">
              This document should be generated by Claude using the Master Template schema.
            </p>

            <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
              <button
                className="inline-flex items-center justify-center rounded-[var(--radius-md)] bg-action-primary px-5 py-2.5 text-sm font-semibold text-content-inverse shadow-[var(--shadow-xs)] transition-all hover:opacity-90 active:scale-95 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-action-primary"
                type="button"
                onClick={handleBrowseClick}
              >
                Browse Files
              </button>
              <button
                className="inline-flex items-center justify-center rounded-[var(--radius-md)] border border-border-default bg-surface-panel px-5 py-2.5 text-sm font-medium text-content-secondary transition-all hover:bg-surface-subtle hover:text-content-primary active:scale-95 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-action-primary"
                type="button"
                onClick={handlePasteClick}
              >
                Paste Markdown
              </button>
            </div>
          </motion.div>
        ) : (
          <motion.div
            key="summary-card"
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.96 }}
            transition={{ duration: 0.2 }}
            className="rounded-[var(--radius-xl)] border border-border-default bg-surface-panel p-6 shadow-[var(--shadow-md)]"
          >
            <div className="flex items-start gap-4">
              <div className="grid size-12 shrink-0 place-items-center rounded-[var(--radius-lg)] bg-emerald-500/10 font-display text-xl font-bold text-emerald-500">
                ✓
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                  <h3 className="truncate font-display text-lg font-semibold text-content-primary">
                    {file.name}
                  </h3>
                  <span className="inline-flex self-start rounded-[var(--radius-sm)] bg-emerald-500/10 px-2 py-1 text-xs font-semibold text-emerald-500">
                    Ready to Import
                  </span>
                </div>
                <dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-2 sm:grid-cols-3">
                  <div>
                    <dt className="font-mono text-[10px] uppercase tracking-wider text-content-muted">File Size</dt>
                    <dd className="mt-1 text-sm font-medium text-content-secondary">{formatBytes(file.size)}</dd>
                  </div>
                  <div>
                    <dt className="font-mono text-[10px] uppercase tracking-wider text-content-muted">Last Modified</dt>
                    <dd className="mt-1 text-sm font-medium text-content-secondary">{formatDate(file.lastModified)}</dd>
                  </div>
                  <div className="col-span-2 sm:col-span-1">
                    <dt className="font-mono text-[10px] uppercase tracking-wider text-content-muted">Format</dt>
                    <dd className="mt-1 text-sm font-medium text-content-secondary">Markdown Document (.md)</dd>
                  </div>
                </dl>
              </div>
            </div>

            <div className="mt-8 flex flex-col justify-end gap-3 border-t border-border-subtle pt-6 sm:flex-row">
              <button
                className="inline-flex items-center justify-center rounded-[var(--radius-md)] border border-border-default bg-surface-panel px-5 py-2.5 text-sm font-medium text-content-secondary transition-all hover:bg-surface-subtle hover:text-content-primary active:scale-95"
                type="button"
                onClick={handleReplaceFile}
              >
                Replace File
              </button>
              <button
                className="inline-flex items-center justify-center rounded-[var(--radius-md)] bg-action-primary px-5 py-2.5 text-sm font-semibold text-content-inverse shadow-[var(--shadow-xs)] transition-all hover:opacity-90 active:scale-95"
                type="button"
              >
                Import Business Record
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <section className="rounded-[var(--radius-xl)] bg-surface-panel border border-border-subtle p-6" aria-labelledby="wf-heading">
        <h3 id="wf-heading" className="font-display text-lg font-semibold tracking-tight text-content-primary">
          What is a Business Record?
        </h3>
        <p className="mt-2 text-sm leading-6 text-content-secondary">
          A Business Record is a structured document that compiles all key insights and factual datasets about your client engagement (e.g., target audiences, financial metrics, case studies, and marketing strategies) in a schema-compliant markdown format.
        </p>
        <ul className="mt-5 space-y-3.5 text-sm text-content-secondary">
          <li className="flex items-start gap-3">
            <span className="mt-1 text-action-primary text-xs">◆</span>
            <span><strong>Single Source of Truth:</strong> Maintains consistent figures and messaging across all downstream slide decks and exports.</span>
          </li>
          <li className="flex items-start gap-3">
            <span className="mt-1 text-action-primary text-xs">◆</span>
            <span><strong>AI-Ready Schema:</strong> Designed to be generated or updated by LLMs (e.g., Claude) using a strict, standardized layout syntax.</span>
          </li>
          <li className="flex items-start gap-3">
            <span className="mt-1 text-action-primary text-xs">◆</span>
            <span><strong>Dynamic Compiler Feed:</strong> Once imported, our compiler automatically maps this record's tables and text fields into responsive presentation components.</span>
          </li>
        </ul>
      </section>
    </div>
  );
}
