/**
 * The Google Fonts catalogue, as the app sees it.
 *
 * Loaded from `/google-fonts.json`, which is generated by
 * `scripts/build-font-catalog.mjs` and committed. Not bundled: it is ~380KB of
 * data that most sessions never open a font picker to look at, and it has no
 * business in the initial parse.
 *
 * Everything here is about one question: can a family survive the trip out of
 * this app? Three things have to be true, and the catalogue records all three.
 *
 *  1. **It can be drawn.** Any family in the list can be pulled from the Google
 *     Fonts CDN at runtime, so the canvas, the PDF and the PNG/HTML exports (all
 *     of which render from the DOM) are correct for free.
 *  2. **Google Slides can name it.** Slides resolves fonts from the Google Fonts
 *     catalogue, so a family in this list needs nothing installed anywhere.
 *  3. **It can be embedded.** Desktop PowerPoint has no catalogue and substitutes
 *     anything it does not have a file for, so the export has to carry the bytes.
 *     `dir`/`slug`/`regular`/`bold` are where those bytes come from.
 *
 * The generator drops any family without a redistributable licence directory in
 * the google/fonts repository, which is how Google's own brand faces stay out:
 * the API will serve you Google Sans, and putting it inside a file you send a
 * client is not ours to do.
 */

export interface CatalogFont {
  family: string;
  /** 'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace'. */
  category: string;
  /** Rank on fonts.google.com; lower is more used. */
  popularity: number;
  /** Which of 400/500/700 this family actually has, for the stylesheet request. */
  weights: number[];
  /** Licence directory in google/fonts: 'ofl' | 'apache' | 'ufl'. */
  dir: string;
  slug: string;
  regular: string;
  bold: string;
  /** True when the repository only has a variable file. Embeddable, but
   *  PowerPoint draws it at its default instance and fakes the bold. */
  variable: boolean;
}

interface Catalog {
  cdn: string;
  count: number;
  fonts: CatalogFont[];
}

/** The three faces the app ships itself, in `public/fonts`, embedded from local
 *  files rather than fetched. They are also in the catalogue, but the export must
 *  prefer the local copy: it is a real static instance per weight, which is
 *  better than anything the repository has for them. */
export const BUNDLED_FAMILIES = ['Space Grotesk', 'DM Sans', 'JetBrains Mono'] as const;

const bundled = new Set<string>(BUNDLED_FAMILIES);

export function isBundled(family: string): boolean {
  return bundled.has(family);
}

let cache: Catalog | null = null;
let inFlight: Promise<Catalog> | null = null;

/**
 * Load the catalogue, once.
 *
 * Concurrent callers share one request: the picker opening and an export
 * starting in the same second must not fetch 380KB twice.
 */
export function loadCatalog(): Promise<Catalog> {
  if (cache) return Promise.resolve(cache);
  if (inFlight) return inFlight;
  inFlight = fetch('/google-fonts.json')
    .then((res) => {
      if (!res.ok) throw new Error(`Font catalogue unavailable (${res.status})`);
      return res.json() as Promise<Catalog>;
    })
    .then((data) => {
      cache = data;
      inFlight = null;
      return data;
    })
    .catch((err) => {
      // Cleared so a later attempt can retry rather than being stuck on a
      // rejected promise for the rest of the session.
      inFlight = null;
      throw err;
    });
  return inFlight;
}

/** The catalogue if it is already in memory, else null. For render paths that
 *  must not suspend on a fetch. */
export function catalogNow(): Catalog | null {
  return cache;
}

export function fontByFamily(family: string): CatalogFont | undefined {
  return cache?.fonts.find((f) => f.family === family);
}

/** Where the TTF for one weight of a family lives. */
export function fileUrl(font: CatalogFont, weight: 'regular' | 'bold'): string {
  const cdn = cache?.cdn ?? 'https://cdn.jsdelivr.net/gh/google/fonts@main';
  return `${cdn}/${font.dir}/${font.slug}/${encodeURIComponent(font[weight])}`;
}

/**
 * Search.
 *
 * A plain case-insensitive substring on the family name, ranked so that a prefix
 * beats a word start beats anything else. Not fuzzy: font names are things people
 * know and type, and fuzzy matching on 1,900 names mostly produces confident
 * nonsense ("Rob" finding "Bree Serif" because it has the letters).
 */
export function searchFonts(
  fonts: CatalogFont[],
  query: string,
  category: string | null,
  limit: number
): CatalogFont[] {
  const q = query.trim().toLowerCase();
  const pool = category ? fonts.filter((f) => f.category === category) : fonts;
  if (!q) return pool.slice(0, limit);

  const scored: { f: CatalogFont; s: number }[] = [];
  for (const f of pool) {
    const name = f.family.toLowerCase();
    const at = name.indexOf(q);
    if (at === -1) continue;
    scored.push({ f, s: at === 0 ? 3 : name[at - 1] === ' ' ? 2 : 1 });
    // The list is already in popularity order, so stopping early keeps the best
    // known names rather than an arbitrary slice.
    if (scored.length >= limit * 4) break;
  }
  return scored
    .sort((a, b) => b.s - a.s || a.f.popularity - b.f.popularity)
    .slice(0, limit)
    .map((x) => x.f);
}

export const CATEGORIES: { id: string; label: string }[] = [
  { id: 'sans-serif', label: 'Sans' },
  { id: 'serif', label: 'Serif' },
  { id: 'display', label: 'Display' },
  { id: 'monospace', label: 'Mono' },
  { id: 'handwriting', label: 'Script' },
];
